spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zoo_architect?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never

server:
  port: 8081
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

weather:
  api:
    base-url: https://api.open-meteo.com/v1

jwt:
  secret: ${JWT_KEY:$2a$12$rJjJdUgI1NT7EQorqQfmR.EtLq7SDOM2cutE0Z5/9SX9tttd5il2W$2a$12$rJjJdUgI1NT7EQorqQfmR.EtLq7SDOM2cutE0Z5/9SX9tttd5il2W}