insert into zoo_architect.habitats (id, description, imageurl, latitude, longitude, name, temperature, weather_condition)
values  (1, 'Grassland habitats are places that receive more rain than deserts but less precipitation than forests. Most of the plants here are grasses, which don’t need as much water as forest vegetation.', 'https://i.natgeofe.com/k/ae89549c-6b2d-4972-a6ec-752a72f7cf33/grassland-lion-pride.jpg?wp=1&w=2154&h=1212', 37.739279, -101.193689, 'Grasslands', 0, null),
        (2, 'Polar habitats cover the top and bottom of planet Earth at the North and South Poles. The North Pole is surrounded by the Arctic Ocean. There isn’t any land here, just a group of continually shifting ice sheets. Parts of Canada and Greenland are near the North Pole. The South Pole is located on Antarctica. This area has land, but it’s completely covered with a layer of ice that’s almost three miles thick in some places.', 'https://i.natgeofe.com/k/88de42b8-764c-40d2-89ee-e72d55dc95b8/emperor-penguin-chicks.jpg?wp=1&w=718&h=404', 71.711995, -111.482985, 'Polar', 0, null),
        (3, 'Many deserts were formed 8,000 to 10,000 years ago. Some are superhot in the day. In fact the highest temperature ever recorded on Earth was 134°F (56.6°C) in California and Nevada''s Death Valley in 1913. Even though many deserts can reach temperatures of well over 100°F (37.8°C) during the day in summer, they can get cold at night. Why? In most places, clouds and water vapor hold in heat, sort of like a blanket. But deserts don’t have enough clouds and water vapor to do this.', 'https://i.natgeofe.com/k/d35924f6-5eb8-4560-9230-cc330e5faa75/deserts-camel-sahara.jpg?wp=1&w=718&h=404', 27.830551, 0.94716, 'Desert', 0, null),
        (4, 'Some mountains form when the big slabs of rock—called tectonic plates—that make up the Earth’s crust crash into each other. Over millions of years, the sheets of rock push up and over one another, creating the mountain. Others form when vents in the Earth’s surface erupt and spew lava out onto the ground. The lava piles up and cools. Over millions of years, the many layers of hard lava become a mountain.', 'https://i.natgeofe.com/k/e646e458-0186-4f92-88f1-6ce7f3132f67/Bolivia-Andes.jpg?wp=1&w=718&h=504', 46.275698, -114.965056, 'Mountain', 0, null),
        (5, 'In regions of the world where it''s not extremely hot or cold (called temperate regions), the forests are full of trees with wide, thin leaves. These leaves absorb sunlight during the summer. But when the days start getting shorter in the fall, the leaves become dry, change color, and eventually drop off the trees. Trees that drop their leaves in autumn are called deciduous trees. Oaks, elms, ash, and beeches are a few of the deciduous trees that can grow in temperate forests.', 'https://i.natgeofe.com/k/ff68c00e-08c4-4233-80a2-a2a71c0ada1f/backyard-gallery-squirrel.jpg?wp=1&w=718&h=404', 49.828902, 21.032858, 'Temperate Forest', 0, null),
        (6, 'Rivers, creeks, lakes, ponds, and streams are all freshwater habitats. So are wetlands like swamps, which have woody plants and trees; and marshes, which have no trees but lots of grasses and reeds. Freshwater accounts for only three percent of the world’s water. (The rest is saltwater.) But despite that tiny amount, freshwater habitats are homes for more than 100,000 species of plants and animals.', 'https://i.natgeofe.com/k/2b95d49c-c0c1-41ae-ba4a-0f4cb6fea722/brazil-amazon.jpg?wp=1&w=718&h=404', 46.848118, 17.733046, 'Freshwater', 0, null),
        (7, 'Oceans are areas of salty water that fill enormous basins on the Earth’s surface. Even though Earth has one continuous body of saltwater, scientists and geographers divide it into five different sections. From biggest to smallest, they are the Pacific, the Atlantic, the Indian, the Southern, and the Arctic Oceans.', 'https://i.natgeofe.com/k/b07ee88b-1291-439b-a139-e0f87c6222ec/hawaiianbeach.jpg?wp=1&w=718&h=404', 19.044352, -41.188999, 'Ocean', 0, null),
        (8, 'Rainforests are lush, warm, wet habitats. Trees in the rainforest grow very tall because they have to compete with other plants for sunlight. Kapok trees, which are found in tropical rainforests around the world, can grow to 200 feet. The tallest trees spread their branches and leaves blocking the light from the trees below, and creating a canopy over the forest. When one of the big trees dies and falls, the opening lets in more sunlight so that a smaller tree can grow and take its place.', 'https://i.natgeofe.com/k/d7cce383-6b47-4589-8de8-79153f364645/_olympic-park-hoh-forest.jpg?wp=1&w=718&h=404', 1.303598, -65.38985, 'Rainforest', 0, null);
